---

main_user_name: user
admin_email:

apache_mirror: https://archive.apache.org

friendly_networks:

# ntp
ntp_servers:
  # use nearby ntp servers by default
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
  - 0.debian.pool.ntp.org iburst
  - 1.debian.pool.ntp.org iburst
  - 2.debian.pool.ntp.org iburst
  - 3.debian.pool.ntp.org iburst
