---

- name: enable firewall
  ufw: rule=allow port={{ item }} from={{ other_private_ip }} to={{ my_private_ip }}
  with_items:
    - 655

- name: install tinc
  apt: >
    name=tinc
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: ensure tinc vpn name directory exists
  file: >
    path=/etc/tinc/{{ vpn_name }}/hosts
    recurse=True
    state=directory

- name: ensure tinc.conf exists for vpn name
  template: >
    src=tinc.conf.j2
    dest=/etc/tinc/{{ vpn_name }}/tinc.conf

- name: ensure tinc address is properly set in tinc host file
  lineinfile: >
    dest=/etc/tinc/{{ vpn_name }}/hosts/{{ ansible_hostname | regex_replace('-', '') }}
    line="Address = {{ my_private_ip }}"
    create=yes
  notify:
    - restart tinc

- name: ensure subnet ip address is properly set in tinc host file
  lineinfile: >
    dest=/etc/tinc/{{ vpn_name }}/hosts/{{ ansible_hostname | regex_replace('-', '') }}
    line="Subnet = {{ tinc_private_ip }}/32"
    create=yes
  notify:
    - restart tinc

- name: create /etc/tinc/nets.boot file from template
  template: >
    src=nets.boot.j2
    dest=/etc/tinc/nets.boot
  notify:
    - restart tinc

- name: create tinc private key
  shell: tincd -n {{ vpn_name }} -K4096
  args:
    creates: /etc/tinc/{{ vpn_name }}/rsa_key.priv

- name: create tinc-up file
  template: >
    src=tinc-up.j2
    dest=/etc/tinc/{{ vpn_name }}/tinc-up
    mode=0755

- name: create tinc-down file
  template: >
    src=tinc-down.j2
    dest=/etc/tinc/{{ vpn_name }}/tinc-down
    mode=0755
  notify:
    - restart tinc

- name: fetch tinc hosts file after private key creation
  fetch: >
    src=/etc/tinc/{{ vpn_name }}/hosts/{{ ansible_hostname | regex_replace('-', '') }}
    dest=fetch/{{ ansible_hostname | regex_replace('-', '') }}
    flat=yes
  notify:
    - restart tinc

# so this will unenessearily copy the hosts file but still should be ok
- name: sync the fetched hosts files on each host
  synchronize:
    src: fetch/
    dest: /etc/tinc/{{ vpn_name }}/hosts/
    rsync_opts:
      - "--exclude=.id_rsa.pub"
  notify:
    - restart tinc

# finally ensure tinc is actually running
- name: ensure tinc is running
  service: >
    name=tinc
    state=started
