
- name: ensure hosts file contains relevant internal lines
  lineinfile: >
    dest=/etc/hosts
    line="{{ item.ip }} {{ item.name }}"
    create=yes
  with_items:
      - { ip: "{{ tinc_private_ip }}", name: "{{ my_internal_hostname }}"}
      - { ip: "{{ tinc_other_ip }}", name: "{{ other_internal_hostname }}"}
