---
# Defines tasks applicable across all machines in the infrastructure.

- name: 'Add debian backports repository'
  apt_repository: repo="deb http://http.debian.net/debian {{ ansible_distribution_release}}-backports main" state=present update_cache=yes
  when: ansible_distribution_release == "squeeze" or ansible_distribution_release == "jessie"
  tags: deps

- name: Update apt cache
  apt: update_cache=yes
  tags: deps

- name: Upgrade all safe packages
  apt: upgrade=safe
  tags: deps

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - apticron
    - build-essential
    - debian-goodies
    - git
    - htop
    - iftop
    - iotop
    - atop
    - python-software-properties
    - tmux
    - sudo
    - unattended-upgrades
    - vim
    - python-pip
    - python-pip-whl
    - supervisor
  tags: deps

- name: Set timezone to UTC
  action: shell echo Etc/UTC > /etc/timezone

- name: Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime

- name: Reconfigure tzdata
  action: command dpkg-reconfigure -f noninteractive tzdata

- name: Apticron email configuration
  template: src=etc/apticron/apticron.conf.j2 dest=/etc/apticron/apticron.conf
  tags: apticron

- include: users.yml
  tags: users

- include: ufw.yml
  tags: ufw

- include: ntp.yml
  tags: ntp

- include: hosts.yml
  tags: hosts
