---

- name: ensure so passwords for sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

- name: Create user accounts
  user: name={{ item }} state=present shell="/bin/bash" groups=sudo
  with_items:
    - user

- name: Upload ssh keys for user
  authorized_key: user=user key="{{ item }}"
  with_file:
    - pub_keys/user1.pub
    - pub_keys/user2.pub
